// tool.v1 — how a built tool is described and called (Tool Builder T0).
//
// Not an RPC service: these are the payloads that cross the Tool Builder's
// boundaries, carried as protojson. The builder compiles a project's gx.yml and
// tool.yml files (glxymesh.com/spec) into a Manifest; the registry stores it and
// the gateway lists and routes from it without waking any code (T2). The
// gateway sends a project's Lambda an InvokeEvent and reads back an
// InvokeResult; every outbound request from that Lambda carries an egress token
// whose claims are an EgressGrant (D30).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tool/v1/tool.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_KIND_HTTP        Kind = 1 // a request template the egress gateway runs; no code
	Kind_KIND_FUNCTION    Kind = 2 // a run function in the project's one Lambda
	Kind_KIND_SERVER      Kind = 3 // a whole MCP server in its own Lambda
	Kind_KIND_BUILTIN     Kind = 4 // a platform tool switched on in gx.yml
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HTTP",
		2: "KIND_FUNCTION",
		3: "KIND_SERVER",
		4: "KIND_BUILTIN",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HTTP":        1,
		"KIND_FUNCTION":    2,
		"KIND_SERVER":      3,
		"KIND_BUILTIN":     4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_v1_tool_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_tool_v1_tool_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

type Lang int32

const (
	Lang_LANG_UNSPECIFIED Lang = 0
	Lang_LANG_GO          Lang = 1
	Lang_LANG_NODE        Lang = 2
	Lang_LANG_PYTHON      Lang = 3
)

// Enum value maps for Lang.
var (
	Lang_name = map[int32]string{
		0: "LANG_UNSPECIFIED",
		1: "LANG_GO",
		2: "LANG_NODE",
		3: "LANG_PYTHON",
	}
	Lang_value = map[string]int32{
		"LANG_UNSPECIFIED": 0,
		"LANG_GO":          1,
		"LANG_NODE":        2,
		"LANG_PYTHON":      3,
	}
)

func (x Lang) Enum() *Lang {
	p := new(Lang)
	*p = x
	return p
}

func (x Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_v1_tool_proto_enumTypes[1].Descriptor()
}

func (Lang) Type() protoreflect.EnumType {
	return &file_tool_v1_tool_proto_enumTypes[1]
}

func (x Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lang.Descriptor instead.
func (Lang) EnumDescriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

type OutputFormat int32

const (
	OutputFormat_OUTPUT_FORMAT_UNSPECIFIED OutputFormat = 0 // the project default
	OutputFormat_OUTPUT_FORMAT_TOON        OutputFormat = 1
	OutputFormat_OUTPUT_FORMAT_JSON        OutputFormat = 2
	OutputFormat_OUTPUT_FORMAT_TEXT        OutputFormat = 3
)

// Enum value maps for OutputFormat.
var (
	OutputFormat_name = map[int32]string{
		0: "OUTPUT_FORMAT_UNSPECIFIED",
		1: "OUTPUT_FORMAT_TOON",
		2: "OUTPUT_FORMAT_JSON",
		3: "OUTPUT_FORMAT_TEXT",
	}
	OutputFormat_value = map[string]int32{
		"OUTPUT_FORMAT_UNSPECIFIED": 0,
		"OUTPUT_FORMAT_TOON":        1,
		"OUTPUT_FORMAT_JSON":        2,
		"OUTPUT_FORMAT_TEXT":        3,
	}
)

func (x OutputFormat) Enum() *OutputFormat {
	p := new(OutputFormat)
	*p = x
	return p
}

func (x OutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_v1_tool_proto_enumTypes[2].Descriptor()
}

func (OutputFormat) Type() protoreflect.EnumType {
	return &file_tool_v1_tool_proto_enumTypes[2]
}

func (x OutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputFormat.Descriptor instead.
func (OutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

type SecretMode int32

const (
	SecretMode_SECRET_MODE_UNSPECIFIED SecretMode = 0
	// The egress gateway adds the key on its bound hosts; code never holds it.
	SecretMode_SECRET_MODE_EGRESS SecretMode = 1
	// Code reads the key for one call with ctx.secret_value, only after a person
	// approved that key for that tool. For SDKs that sign requests themselves
	// and for server tools, whose calls the egress gateway can't open.
	SecretMode_SECRET_MODE_PASS_IN SecretMode = 2
)

// Enum value maps for SecretMode.
var (
	SecretMode_name = map[int32]string{
		0: "SECRET_MODE_UNSPECIFIED",
		1: "SECRET_MODE_EGRESS",
		2: "SECRET_MODE_PASS_IN",
	}
	SecretMode_value = map[string]int32{
		"SECRET_MODE_UNSPECIFIED": 0,
		"SECRET_MODE_EGRESS":      1,
		"SECRET_MODE_PASS_IN":     2,
	}
)

func (x SecretMode) Enum() *SecretMode {
	p := new(SecretMode)
	*p = x
	return p
}

func (x SecretMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretMode) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_v1_tool_proto_enumTypes[3].Descriptor()
}

func (SecretMode) Type() protoreflect.EnumType {
	return &file_tool_v1_tool_proto_enumTypes[3]
}

func (x SecretMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretMode.Descriptor instead.
func (SecretMode) EnumDescriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

type ErrorKind int32

const (
	ErrorKind_ERROR_KIND_UNSPECIFIED ErrorKind = 0
	// Raised on purpose (ToolError): the model reads the message and can act.
	ErrorKind_ERROR_KIND_TOOL ErrorKind = 1
	// A bug: the model gets a fixed sentence and the owner the log.
	ErrorKind_ERROR_KIND_CRASH ErrorKind = 2
)

// Enum value maps for ErrorKind.
var (
	ErrorKind_name = map[int32]string{
		0: "ERROR_KIND_UNSPECIFIED",
		1: "ERROR_KIND_TOOL",
		2: "ERROR_KIND_CRASH",
	}
	ErrorKind_value = map[string]int32{
		"ERROR_KIND_UNSPECIFIED": 0,
		"ERROR_KIND_TOOL":        1,
		"ERROR_KIND_CRASH":       2,
	}
)

func (x ErrorKind) Enum() *ErrorKind {
	p := new(ErrorKind)
	*p = x
	return p
}

func (x ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_v1_tool_proto_enumTypes[4].Descriptor()
}

func (ErrorKind) Type() protoreflect.EnumType {
	return &file_tool_v1_tool_proto_enumTypes[4]
}

func (x ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorKind.Descriptor instead.
func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{4}
}

// Why the egress gateway let an outside request through or stopped it.
type EgressDecision int32

const (
	EgressDecision_EGRESS_DECISION_UNSPECIFIED         EgressDecision = 0
	EgressDecision_EGRESS_DECISION_ALLOWED             EgressDecision = 1
	EgressDecision_EGRESS_DECISION_HOST_NOT_ALLOWED    EgressDecision = 2 // not on the tool's allow-list
	EgressDecision_EGRESS_DECISION_PRIVATE_ADDRESS     EgressDecision = 3 // resolved into a private or metadata range
	EgressDecision_EGRESS_DECISION_KEY_ON_UNBOUND_HOST EgressDecision = 4 // a redirect would carry a key off its hosts
	EgressDecision_EGRESS_DECISION_TOO_LARGE           EgressDecision = 5 // the response passed the size cap
	EgressDecision_EGRESS_DECISION_FAILED              EgressDecision = 6 // the upstream didn't answer in time or at all
)

// Enum value maps for EgressDecision.
var (
	EgressDecision_name = map[int32]string{
		0: "EGRESS_DECISION_UNSPECIFIED",
		1: "EGRESS_DECISION_ALLOWED",
		2: "EGRESS_DECISION_HOST_NOT_ALLOWED",
		3: "EGRESS_DECISION_PRIVATE_ADDRESS",
		4: "EGRESS_DECISION_KEY_ON_UNBOUND_HOST",
		5: "EGRESS_DECISION_TOO_LARGE",
		6: "EGRESS_DECISION_FAILED",
	}
	EgressDecision_value = map[string]int32{
		"EGRESS_DECISION_UNSPECIFIED":         0,
		"EGRESS_DECISION_ALLOWED":             1,
		"EGRESS_DECISION_HOST_NOT_ALLOWED":    2,
		"EGRESS_DECISION_PRIVATE_ADDRESS":     3,
		"EGRESS_DECISION_KEY_ON_UNBOUND_HOST": 4,
		"EGRESS_DECISION_TOO_LARGE":           5,
		"EGRESS_DECISION_FAILED":              6,
	}
)

func (x EgressDecision) Enum() *EgressDecision {
	p := new(EgressDecision)
	*p = x
	return p
}

func (x EgressDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_v1_tool_proto_enumTypes[5].Descriptor()
}

func (EgressDecision) Type() protoreflect.EnumType {
	return &file_tool_v1_tool_proto_enumTypes[5]
}

func (x EgressDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressDecision.Descriptor instead.
func (EgressDecision) EnumDescriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{5}
}

// Where a key may travel and how it is attached. Values are never here: they
// stay in the vault and are fetched per call.
type SecretBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hosts         []string               `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"` // a host covers its subdomains
	Mode          SecretMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=tool.v1.SecretMode" json:"mode,omitempty"`
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`      // "Authorization: Bearer {value}"; egress only
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`        // a query parameter name; egress only
	Approved      bool                   `protobuf:"varint,6,opt,name=approved,proto3" json:"approved,omitempty"` // pass-in keys and new hosts wait for a person
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretBinding) Reset() {
	*x = SecretBinding{}
	mi := &file_tool_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretBinding) ProtoMessage() {}

func (x *SecretBinding) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretBinding.ProtoReflect.Descriptor instead.
func (*SecretBinding) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

func (x *SecretBinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretBinding) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *SecretBinding) GetMode() SecretMode {
	if x != nil {
		return x.Mode
	}
	return SecretMode_SECRET_MODE_UNSPECIFIED
}

func (x *SecretBinding) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SecretBinding) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SecretBinding) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"` // the host is fixed; inputs fill {placeholders} after it
	Query         map[string]string      `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BodyJson      string                 `protobuf:"bytes,5,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`             // a JSON template, empty for none
	ResponsePick  string                 `protobuf:"bytes,6,opt,name=response_pick,json=responsePick,proto3" json:"response_pick,omitempty"` // JMESPath over the upstream JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *HttpRequest) GetResponsePick() string {
	if x != nil {
		return x.ResponsePick
	}
	return ""
}

type ServerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"` // a zip's start file, or empty for an image
	Build         string                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"` // a Dockerfile, or empty for a zip
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEntry) Reset() {
	*x = ServerEntry{}
	mi := &file_tool_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEntry) ProtoMessage() {}

func (x *ServerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEntry.ProtoReflect.Descriptor instead.
func (*ServerEntry) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *ServerEntry) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *ServerEntry) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *ServerEntry) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ToolSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Kind            Kind                   `protobuf:"varint,4,opt,name=kind,proto3,enum=tool.v1.Kind" json:"kind,omitempty"`
	ReadOnly        bool                   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	InputSchemaJson string                 `protobuf:"bytes,6,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"` // generated from inputs; what tools/list sends
	OutputFormat    OutputFormat           `protobuf:"varint,7,opt,name=output_format,json=outputFormat,proto3,enum=tool.v1.OutputFormat" json:"output_format,omitempty"`
	OutputAs        string                 `protobuf:"bytes,8,opt,name=output_as,json=outputAs,proto3" json:"output_as,omitempty"`
	NetworkAllow    []string               `protobuf:"bytes,9,rep,name=network_allow,json=networkAllow,proto3" json:"network_allow,omitempty"`
	Secrets         []*SecretBinding       `protobuf:"bytes,10,rep,name=secrets,proto3" json:"secrets,omitempty"`
	TimeoutMs       int32                  `protobuf:"varint,11,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MemoryMb        int32                  `protobuf:"varint,12,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Http            *HttpRequest           `protobuf:"bytes,13,opt,name=http,proto3" json:"http,omitempty"`     // KIND_HTTP only
	Server          *ServerEntry           `protobuf:"bytes,14,opt,name=server,proto3" json:"server,omitempty"` // KIND_SERVER only
	// Tools a server listed when the builder started it once, so the gateway can
	// list them without waking it. KIND_SERVER only.
	Served []*ToolSpec `protobuf:"bytes,15,rep,name=served,proto3" json:"served,omitempty"`
	// host:port pairs the code may open a TCP connection to through the egress
	// gateway's /connect, for databases and other protocols that aren't HTTPS.
	// A host may be a vault host, {NAME}:5432.
	NetworkConnect []string `protobuf:"bytes,16,rep,name=network_connect,json=networkConnect,proto3" json:"network_connect,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	mi := &file_tool_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *ToolSpec) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *ToolSpec) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *ToolSpec) GetOutputFormat() OutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

func (x *ToolSpec) GetOutputAs() string {
	if x != nil {
		return x.OutputAs
	}
	return ""
}

func (x *ToolSpec) GetNetworkAllow() []string {
	if x != nil {
		return x.NetworkAllow
	}
	return nil
}

func (x *ToolSpec) GetSecrets() []*SecretBinding {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ToolSpec) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ToolSpec) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ToolSpec) GetHttp() *HttpRequest {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *ToolSpec) GetServer() *ServerEntry {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ToolSpec) GetServed() []*ToolSpec {
	if x != nil {
		return x.Served
	}
	return nil
}

func (x *ToolSpec) GetNetworkConnect() []string {
	if x != nil {
		return x.NetworkConnect
	}
	return nil
}

// What MCP clients show for the project (D29).
type ServerIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	WebsiteUrl    string                 `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerIdentity) Reset() {
	*x = ServerIdentity{}
	mi := &file_tool_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerIdentity) ProtoMessage() {}

func (x *ServerIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerIdentity.ProtoReflect.Descriptor instead.
func (*ServerIdentity) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *ServerIdentity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ServerIdentity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServerIdentity) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *ServerIdentity) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

// One build of a project: everything the gateway needs to list and route its
// tools. Revision counts builds; the gateway only moves forward.
type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Lang          Lang                   `protobuf:"varint,3,opt,name=lang,proto3,enum=tool.v1.Lang" json:"lang,omitempty"`
	Revision      int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	SourceSha256  string                 `protobuf:"bytes,5,opt,name=source_sha256,json=sourceSha256,proto3" json:"source_sha256,omitempty"` // of the pushed source, so a build can be repeated
	Server        *ServerIdentity        `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	Tools         []*ToolSpec            `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	Builtins      []string               `protobuf:"bytes,8,rep,name=builtins,proto3" json:"builtins,omitempty"`
	BuiltAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_tool_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *Manifest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Manifest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Manifest) GetLang() Lang {
	if x != nil {
		return x.Lang
	}
	return Lang_LANG_UNSPECIFIED
}

func (x *Manifest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Manifest) GetSourceSha256() string {
	if x != nil {
		return x.SourceSha256
	}
	return ""
}

func (x *Manifest) GetServer() *ServerIdentity {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Manifest) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Manifest) GetBuiltins() []string {
	if x != nil {
		return x.Builtins
	}
	return nil
}

func (x *Manifest) GetBuiltAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuiltAt
	}
	return nil
}

// Who is calling, as code may see it: never an email or a token.
type Caller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // the MCP client the person allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caller) Reset() {
	*x = Caller{}
	mi := &file_tool_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caller) ProtoMessage() {}

func (x *Caller) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caller.ProtoReflect.Descriptor instead.
func (*Caller) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{6}
}

func (x *Caller) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Caller) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Caller) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Caller) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// The gateway's Invoke payload to a project's Lambda for one tools/call.
type InvokeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // also on the egress gateway's and the gateway's logs
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // already checked against the input schema
	Caller        *Caller                `protobuf:"bytes,4,opt,name=caller,proto3" json:"caller,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Sent with every request to the egress gateway; it expires at the deadline.
	EgressToken   string `protobuf:"bytes,6,opt,name=egress_token,json=egressToken,proto3" json:"egress_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeEvent) Reset() {
	*x = InvokeEvent{}
	mi := &file_tool_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeEvent) ProtoMessage() {}

func (x *InvokeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeEvent.ProtoReflect.Descriptor instead.
func (*InvokeEvent) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InvokeEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *InvokeEvent) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *InvokeEvent) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *InvokeEvent) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *InvokeEvent) GetEgressToken() string {
	if x != nil {
		return x.EgressToken
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "info", "warn", "error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_tool_v1_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{8}
}

func (x *LogLine) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// What the Lambda returns. Logs ride back with the result, so tool Lambdas
// never write to CloudWatch and the console never reads it.
type InvokeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // empty on error
	ErrorKind     ErrorKind              `protobuf:"varint,2,opt,name=error_kind,json=errorKind,proto3,enum=tool.v1.ErrorKind" json:"error_kind,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Logs          []*LogLine             `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"` // at most 64 KB; the rest is dropped
	LogsTruncated bool                   `protobuf:"varint,5,opt,name=logs_truncated,json=logsTruncated,proto3" json:"logs_truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResult) Reset() {
	*x = InvokeResult{}
	mi := &file_tool_v1_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResult) ProtoMessage() {}

func (x *InvokeResult) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResult.ProtoReflect.Descriptor instead.
func (*InvokeResult) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *InvokeResult) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_UNSPECIFIED
}

func (x *InvokeResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InvokeResult) GetLogs() []*LogLine {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *InvokeResult) GetLogsTruncated() bool {
	if x != nil {
		return x.LogsTruncated
	}
	return false
}

// The claims behind an egress token. The egress gateway allows a request only
// to the tool's own hosts and attaches only the tool's own keys, until the
// call's deadline.
type EgressGrant struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CallId           string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Org              string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Project          string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Tool             string                 `protobuf:"bytes,4,opt,name=tool,proto3" json:"tool,omitempty"`
	ManifestRevision int64                  `protobuf:"varint,5,opt,name=manifest_revision,json=manifestRevision,proto3" json:"manifest_revision,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// A person is watching this call (a test, or a call tried on a draft): the
	// egress gateway keeps each request's detail for them to read back.
	Trace         bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressGrant) Reset() {
	*x = EgressGrant{}
	mi := &file_tool_v1_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressGrant) ProtoMessage() {}

func (x *EgressGrant) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressGrant.ProtoReflect.Descriptor instead.
func (*EgressGrant) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{10}
}

func (x *EgressGrant) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EgressGrant) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *EgressGrant) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *EgressGrant) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *EgressGrant) GetManifestRevision() int64 {
	if x != nil {
		return x.ManifestRevision
	}
	return 0
}

func (x *EgressGrant) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EgressGrant) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

// The gateway's request to the egress gateway to run one http tool (T3). The
// egress token in the Authorization header names the call, the tool and the
// manifest revision; the egress gateway reads the spec from the registry, never
// from the caller.
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArgumentsJson string                 `protobuf:"bytes,1,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // already checked against the input schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{11}
}

func (x *ExecRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// One outside request. The request log keeps fields 1-8 only: no path or
// query, which can carry arguments, and never a key. The rest is filled for a
// traced call alone, for the person watching it, with every key value
// replaced by its name.
type EgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 0 when nothing came back
	BytesOut      int64                  `protobuf:"varint,5,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	BytesIn       int64                  `protobuf:"varint,6,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	DurationMs    int32                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Decision      EgressDecision         `protobuf:"varint,8,opt,name=decision,proto3,enum=tool.v1.EgressDecision" json:"decision,omitempty"`
	Url           string                 `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*Header              `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty"` // as sent
	Answer        string                 `protobuf:"bytes,11,opt,name=answer,proto3" json:"answer,omitempty"`   // the start of the body that came back
	AnswerHeaders []*Header              `protobuf:"bytes,12,rep,name=answer_headers,json=answerHeaders,proto3" json:"answer_headers,omitempty"`
	Error         string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"` // why it was refused or got no answer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRequest) Reset() {
	*x = EgressRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRequest) ProtoMessage() {}

func (x *EgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRequest.ProtoReflect.Descriptor instead.
func (*EgressRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{12}
}

func (x *EgressRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *EgressRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EgressRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EgressRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EgressRequest) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *EgressRequest) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *EgressRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *EgressRequest) GetDecision() EgressDecision {
	if x != nil {
		return x.Decision
	}
	return EgressDecision_EGRESS_DECISION_UNSPECIFIED
}

func (x *EgressRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EgressRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EgressRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *EgressRequest) GetAnswerHeaders() []*Header {
	if x != nil {
		return x.AnswerHeaders
	}
	return nil
}

func (x *EgressRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A traced call's requests, from GET /trace with the call's egress token.
type EgressTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*EgressRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressTrace) Reset() {
	*x = EgressTrace{}
	mi := &file_tool_v1_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressTrace) ProtoMessage() {}

func (x *EgressTrace) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressTrace.ProtoReflect.Descriptor instead.
func (*EgressTrace) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{13}
}

func (x *EgressTrace) GetRequests() []*EgressRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ExecResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *InvokeResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Requests      []*EgressRequest       `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_tool_v1_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{14}
}

func (x *ExecResult) GetResult() *InvokeResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecResult) GetRequests() []*EgressRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_tool_v1_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{15}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A passed-in key's value, from GET /secret/{name} with the call's egress
// token: only a key the live tool binds with SECRET_MODE_PASS_IN, which a
// person approved when the revision was published.
type SecretValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretValue) Reset() {
	*x = SecretValue{}
	mi := &file_tool_v1_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretValue) ProtoMessage() {}

func (x *SecretValue) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretValue.ProtoReflect.Descriptor instead.
func (*SecretValue) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{16}
}

func (x *SecretValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A request tool code sends out through the egress gateway (T4a), in protobuf
// binary to POST /fetch with the call's egress token. The egress gateway holds
// it to the tool's allow-list, adds the tool's keys on their bound hosts, fills
// {{secret:NAME}} placeholders only there, and refuses the rest.
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{17}
}

func (x *FetchRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// The upstream's answer, or why there is none: a refused or failed request has
// status 0, its decision, and an error the tool can report.
type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*Header              `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Decision      EgressDecision         `protobuf:"varint,4,opt,name=decision,proto3,enum=tool.v1.EgressDecision" json:"decision,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{18}
}

func (x *FetchResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FetchResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FetchResponse) GetDecision() EgressDecision {
	if x != nil {
		return x.Decision
	}
	return EgressDecision_EGRESS_DECISION_UNSPECIFIED
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tool_v1_tool_proto protoreflect.FileDescriptor

const file_tool_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x12tool/v1/tool.proto\x12\atool.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\rSecretBinding\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05hosts\x18\x02 \x03(\tR\x05hosts\x12'\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x13.tool.v1.SecretModeR\x04mode\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12\x1a\n" +
	"\bapproved\x18\x06 \x01(\bR\bapproved\"\xe3\x02\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x125\n" +
	"\x05query\x18\x03 \x03(\v2\x1f.tool.v1.HttpRequest.QueryEntryR\x05query\x12;\n" +
	"\aheaders\x18\x04 \x03(\v2!.tool.v1.HttpRequest.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tbody_json\x18\x05 \x01(\tR\bbodyJson\x12#\n" +
	"\rresponse_pick\x18\x06 \x01(\tR\fresponsePick\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\vServerEntry\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\xda\x04\n" +
	"\bToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\x04kind\x18\x04 \x01(\x0e2\r.tool.v1.KindR\x04kind\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\x12*\n" +
	"\x11input_schema_json\x18\x06 \x01(\tR\x0finputSchemaJson\x12:\n" +
	"\routput_format\x18\a \x01(\x0e2\x15.tool.v1.OutputFormatR\foutputFormat\x12\x1b\n" +
	"\toutput_as\x18\b \x01(\tR\boutputAs\x12#\n" +
	"\rnetwork_allow\x18\t \x03(\tR\fnetworkAllow\x120\n" +
	"\asecrets\x18\n" +
	" \x03(\v2\x16.tool.v1.SecretBindingR\asecrets\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\v \x01(\x05R\ttimeoutMs\x12\x1b\n" +
	"\tmemory_mb\x18\f \x01(\x05R\bmemoryMb\x12(\n" +
	"\x04http\x18\r \x01(\v2\x14.tool.v1.HttpRequestR\x04http\x12,\n" +
	"\x06server\x18\x0e \x01(\v2\x14.tool.v1.ServerEntryR\x06server\x12)\n" +
	"\x06served\x18\x0f \x03(\v2\x11.tool.v1.ToolSpecR\x06served\x12'\n" +
	"\x0fnetwork_connect\x18\x10 \x03(\tR\x0enetworkConnect\"\x84\x01\n" +
	"\x0eServerIdentity\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vwebsite_url\x18\x03 \x01(\tR\n" +
	"websiteUrl\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\"\xc7\x02\n" +
	"\bManifest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12!\n" +
	"\x04lang\x18\x03 \x01(\x0e2\r.tool.v1.LangR\x04lang\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12#\n" +
	"\rsource_sha256\x18\x05 \x01(\tR\fsourceSha256\x12/\n" +
	"\x06server\x18\x06 \x01(\v2\x17.tool.v1.ServerIdentityR\x06server\x12'\n" +
	"\x05tools\x18\a \x03(\v2\x11.tool.v1.ToolSpecR\x05tools\x12\x1a\n" +
	"\bbuiltins\x18\b \x03(\tR\bbuiltins\x125\n" +
	"\bbuilt_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\abuiltAt\"j\n" +
	"\x06Caller\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"\xe5\x01\n" +
	"\vInvokeEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12'\n" +
	"\x06caller\x18\x04 \x01(\v2\x0f.tool.v1.CallerR\x06caller\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12!\n" +
	"\fegress_token\x18\x06 \x01(\tR\vegressToken\"e\n" +
	"\aLogLine\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd4\x01\n" +
	"\fInvokeResult\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x121\n" +
	"\n" +
	"error_kind\x18\x02 \x01(\x0e2\x12.tool.v1.ErrorKindR\terrorKind\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12$\n" +
	"\x04logs\x18\x04 \x03(\v2\x10.tool.v1.LogLineR\x04logs\x12%\n" +
	"\x0elogs_truncated\x18\x05 \x01(\bR\rlogsTruncated\"\xe4\x01\n" +
	"\vEgressGrant\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04tool\x18\x04 \x01(\tR\x04tool\x12+\n" +
	"\x11manifest_revision\x18\x05 \x01(\x03R\x10manifestRevision\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05trace\x18\a \x01(\bR\x05trace\"4\n" +
	"\vExecRequest\x12%\n" +
	"\x0earguments_json\x18\x01 \x01(\tR\rargumentsJson\"\xb0\x03\n" +
	"\rEgressRequest\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1b\n" +
	"\tbytes_out\x18\x05 \x01(\x03R\bbytesOut\x12\x19\n" +
	"\bbytes_in\x18\x06 \x01(\x03R\abytesIn\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x05R\n" +
	"durationMs\x123\n" +
	"\bdecision\x18\b \x01(\x0e2\x17.tool.v1.EgressDecisionR\bdecision\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12)\n" +
	"\aheaders\x18\n" +
	" \x03(\v2\x0f.tool.v1.HeaderR\aheaders\x12\x16\n" +
	"\x06answer\x18\v \x01(\tR\x06answer\x126\n" +
	"\x0eanswer_headers\x18\f \x03(\v2\x0f.tool.v1.HeaderR\ranswerHeaders\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"A\n" +
	"\vEgressTrace\x122\n" +
	"\brequests\x18\x01 \x03(\v2\x16.tool.v1.EgressRequestR\brequests\"o\n" +
	"\n" +
	"ExecResult\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.tool.v1.InvokeResultR\x06result\x122\n" +
	"\brequests\x18\x02 \x03(\v2\x16.tool.v1.EgressRequestR\brequests\"2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"7\n" +
	"\vSecretValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"w\n" +
	"\fFetchRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12)\n" +
	"\aheaders\x18\x03 \x03(\v2\x0f.tool.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"\xb1\x01\n" +
	"\rFetchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12)\n" +
	"\aheaders\x18\x02 \x03(\v2\x0f.tool.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x123\n" +
	"\bdecision\x18\x04 \x01(\x0e2\x17.tool.v1.EgressDecisionR\bdecision\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*a\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_HTTP\x10\x01\x12\x11\n" +
	"\rKIND_FUNCTION\x10\x02\x12\x0f\n" +
	"\vKIND_SERVER\x10\x03\x12\x10\n" +
	"\fKIND_BUILTIN\x10\x04*I\n" +
	"\x04Lang\x12\x14\n" +
	"\x10LANG_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aLANG_GO\x10\x01\x12\r\n" +
	"\tLANG_NODE\x10\x02\x12\x0f\n" +
	"\vLANG_PYTHON\x10\x03*u\n" +
	"\fOutputFormat\x12\x1d\n" +
	"\x19OUTPUT_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OUTPUT_FORMAT_TOON\x10\x01\x12\x16\n" +
	"\x12OUTPUT_FORMAT_JSON\x10\x02\x12\x16\n" +
	"\x12OUTPUT_FORMAT_TEXT\x10\x03*Z\n" +
	"\n" +
	"SecretMode\x12\x1b\n" +
	"\x17SECRET_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SECRET_MODE_EGRESS\x10\x01\x12\x17\n" +
	"\x13SECRET_MODE_PASS_IN\x10\x02*R\n" +
	"\tErrorKind\x12\x1a\n" +
	"\x16ERROR_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fERROR_KIND_TOOL\x10\x01\x12\x14\n" +
	"\x10ERROR_KIND_CRASH\x10\x02*\xfd\x01\n" +
	"\x0eEgressDecision\x12\x1f\n" +
	"\x1bEGRESS_DECISION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EGRESS_DECISION_ALLOWED\x10\x01\x12$\n" +
	" EGRESS_DECISION_HOST_NOT_ALLOWED\x10\x02\x12#\n" +
	"\x1fEGRESS_DECISION_PRIVATE_ADDRESS\x10\x03\x12'\n" +
	"#EGRESS_DECISION_KEY_ON_UNBOUND_HOST\x10\x04\x12\x1d\n" +
	"\x19EGRESS_DECISION_TOO_LARGE\x10\x05\x12\x1a\n" +
	"\x16EGRESS_DECISION_FAILED\x10\x06B!Z\x1fglxymesh.com/gen/tool/v1;toolv1b\x06proto3"

var (
	file_tool_v1_tool_proto_rawDescOnce sync.Once
	file_tool_v1_tool_proto_rawDescData []byte
)

func file_tool_v1_tool_proto_rawDescGZIP() []byte {
	file_tool_v1_tool_proto_rawDescOnce.Do(func() {
		file_tool_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_v1_tool_proto_rawDesc), len(file_tool_v1_tool_proto_rawDesc)))
	})
	return file_tool_v1_tool_proto_rawDescData
}

var file_tool_v1_tool_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_tool_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tool_v1_tool_proto_goTypes = []any{
	(Kind)(0),                     // 0: tool.v1.Kind
	(Lang)(0),                     // 1: tool.v1.Lang
	(OutputFormat)(0),             // 2: tool.v1.OutputFormat
	(SecretMode)(0),               // 3: tool.v1.SecretMode
	(ErrorKind)(0),                // 4: tool.v1.ErrorKind
	(EgressDecision)(0),           // 5: tool.v1.EgressDecision
	(*SecretBinding)(nil),         // 6: tool.v1.SecretBinding
	(*HttpRequest)(nil),           // 7: tool.v1.HttpRequest
	(*ServerEntry)(nil),           // 8: tool.v1.ServerEntry
	(*ToolSpec)(nil),              // 9: tool.v1.ToolSpec
	(*ServerIdentity)(nil),        // 10: tool.v1.ServerIdentity
	(*Manifest)(nil),              // 11: tool.v1.Manifest
	(*Caller)(nil),                // 12: tool.v1.Caller
	(*InvokeEvent)(nil),           // 13: tool.v1.InvokeEvent
	(*LogLine)(nil),               // 14: tool.v1.LogLine
	(*InvokeResult)(nil),          // 15: tool.v1.InvokeResult
	(*EgressGrant)(nil),           // 16: tool.v1.EgressGrant
	(*ExecRequest)(nil),           // 17: tool.v1.ExecRequest
	(*EgressRequest)(nil),         // 18: tool.v1.EgressRequest
	(*EgressTrace)(nil),           // 19: tool.v1.EgressTrace
	(*ExecResult)(nil),            // 20: tool.v1.ExecResult
	(*Header)(nil),                // 21: tool.v1.Header
	(*SecretValue)(nil),           // 22: tool.v1.SecretValue
	(*FetchRequest)(nil),          // 23: tool.v1.FetchRequest
	(*FetchResponse)(nil),         // 24: tool.v1.FetchResponse
	nil,                           // 25: tool.v1.HttpRequest.QueryEntry
	nil,                           // 26: tool.v1.HttpRequest.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_tool_v1_tool_proto_depIdxs = []int32{
	3,  // 0: tool.v1.SecretBinding.mode:type_name -> tool.v1.SecretMode
	25, // 1: tool.v1.HttpRequest.query:type_name -> tool.v1.HttpRequest.QueryEntry
	26, // 2: tool.v1.HttpRequest.headers:type_name -> tool.v1.HttpRequest.HeadersEntry
	0,  // 3: tool.v1.ToolSpec.kind:type_name -> tool.v1.Kind
	2,  // 4: tool.v1.ToolSpec.output_format:type_name -> tool.v1.OutputFormat
	6,  // 5: tool.v1.ToolSpec.secrets:type_name -> tool.v1.SecretBinding
	7,  // 6: tool.v1.ToolSpec.http:type_name -> tool.v1.HttpRequest
	8,  // 7: tool.v1.ToolSpec.server:type_name -> tool.v1.ServerEntry
	9,  // 8: tool.v1.ToolSpec.served:type_name -> tool.v1.ToolSpec
	1,  // 9: tool.v1.Manifest.lang:type_name -> tool.v1.Lang
	10, // 10: tool.v1.Manifest.server:type_name -> tool.v1.ServerIdentity
	9,  // 11: tool.v1.Manifest.tools:type_name -> tool.v1.ToolSpec
	27, // 12: tool.v1.Manifest.built_at:type_name -> google.protobuf.Timestamp
	12, // 13: tool.v1.InvokeEvent.caller:type_name -> tool.v1.Caller
	27, // 14: tool.v1.InvokeEvent.deadline:type_name -> google.protobuf.Timestamp
	27, // 15: tool.v1.LogLine.at:type_name -> google.protobuf.Timestamp
	4,  // 16: tool.v1.InvokeResult.error_kind:type_name -> tool.v1.ErrorKind
	14, // 17: tool.v1.InvokeResult.logs:type_name -> tool.v1.LogLine
	27, // 18: tool.v1.EgressGrant.expires_at:type_name -> google.protobuf.Timestamp
	27, // 19: tool.v1.EgressRequest.at:type_name -> google.protobuf.Timestamp
	5,  // 20: tool.v1.EgressRequest.decision:type_name -> tool.v1.EgressDecision
	21, // 21: tool.v1.EgressRequest.headers:type_name -> tool.v1.Header
	21, // 22: tool.v1.EgressRequest.answer_headers:type_name -> tool.v1.Header
	18, // 23: tool.v1.EgressTrace.requests:type_name -> tool.v1.EgressRequest
	15, // 24: tool.v1.ExecResult.result:type_name -> tool.v1.InvokeResult
	18, // 25: tool.v1.ExecResult.requests:type_name -> tool.v1.EgressRequest
	21, // 26: tool.v1.FetchRequest.headers:type_name -> tool.v1.Header
	21, // 27: tool.v1.FetchResponse.headers:type_name -> tool.v1.Header
	5,  // 28: tool.v1.FetchResponse.decision:type_name -> tool.v1.EgressDecision
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_tool_v1_tool_proto_init() }
func file_tool_v1_tool_proto_init() {
	if File_tool_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_v1_tool_proto_rawDesc), len(file_tool_v1_tool_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tool_v1_tool_proto_goTypes,
		DependencyIndexes: file_tool_v1_tool_proto_depIdxs,
		EnumInfos:         file_tool_v1_tool_proto_enumTypes,
		MessageInfos:      file_tool_v1_tool_proto_msgTypes,
	}.Build()
	File_tool_v1_tool_proto = out.File
	file_tool_v1_tool_proto_goTypes = nil
	file_tool_v1_tool_proto_depIdxs = nil
}
